apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gnotes-deployment
  labels: 
    app: gnotes
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: gnotes
  template:
    metadata:
      labels:
        app: gnotes
    spec:
      containers:
      - name: gnotes
        image: laguzs/gnotes:1.3
        ports: 
        - containerPort: 5000
        # Reading Env variables from Config map and Secret
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: server-port
        - name: PORT_SWAGGER
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: server-port-swagger
        - name: SERVER
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: server-ip       
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: database-host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: database-port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: database-name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: database-password
        - name: TOKEN_KEY
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: token-key
        - name: LOGGER_LEVEL
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: logger-level
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: node-env          
---
apiVersion: v1
kind: Service
metadata: 
  name: gnotes-service
spec:
  type: NodePort
  selector:
    app: gnotes
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100