apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gnotes-deployment
  labels: 
    app: gnotes
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: gnotes
  template:
    metadata:
      labels:
        app: gnotes
    spec:
      containers:
      - name: gnotes
        image: laguzs/gnotes:1.0
        ports: 
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: server-port       
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: database-name              
        - name: TOKEN_KEY
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: token-key
        - name: LOGGER_LEVEL
          value: debug
        - name: NODE_ENV
          value: development            
---
apiVersion: v1
kind: Service
metadata: 
  name: gnotes-service
spec:
  type: NodePort
  selector:
    app: gnotes
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100