version: '3.8'

services: 
  app:
    image: laguzs/gnotes:1.0
    build: .
    restart: unless-stopped
    network_mode: host
    env_file: ./.env
    ports: 
      - 5000:5000
    volumes:
      - ./:/code

